version: "2.1"

services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /data/plex/radarr/config:/config
      - /data/plex/media/movies:/media
      - /data/plex/sabnzbd/config/Downloads/complete:/downloads
    ports:
        - 7878:7878
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 172.20.0.11

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /data/plex/sabnzbd/config:/config
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 172.20.0.12

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /data/plex/sonarr/config:/config
      - /data/plex/media/tv:/media
      - /data/plex/sabnzbd/config/Downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 172.20.0.13

networks:
  net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
