version: "2.1"

services:
  lonelycraft:
    image: itzg/minecraft-server
    container_name: lonelycraft
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/New_York
      - EULA=TRUE
      - TYPE=PAPER
      - MEMORY=4G
      - USE_AIKAR_FLAGS=true
      # Mod: CoreProtect
      - SPIGET_RESOURCES=8631
    volumes:
      - /data/lonelycraft:/data
    ports:
      - 25565:25565
    restart: unless-stopped
